apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnetjenkinsgithub221024 
  janus-idp.io/tekton: dotnetjenkinsgithub221024
  backstage.io/kubernetes-id: dotnetjenkinsgithub221024
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnetjenkinsgithub221024
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  