apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dotnetjenkinsgithub221024-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/dotnetjenkinsgithub221024-gitops