apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnetjenkinsgithub221024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnetjenkinsgithub221024 
  name: dotnetjenkinsgithub221024
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnetjenkinsgithub221024 
